# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information, site metadata
site_name: RecapTime.dev Wiki
site_url: "https://wiki.recaptime.dev"
site_author: Recap Time Squad and contributors
site_description: >-
  The home of Recap Time Squad's team handbook, its history
  througout the years, and more

# Lock the use-directory-urls flag
use_directory_urls: true

# Repository
docs_dir: content
repo_url: https://mau.dev/recaptime-dev/squad/wiki
repo_name: source at Maunium GitLab
edit_uri: blob/main/content/

# Copyright
copyright: >-
  Copyright &copy; 2023-present Recap Time Squad and contributiors,
  wiki content licensed under CC-BY-SA-4.0 and code samples under MPL-2.0.

# Theme settings
theme:
  # https://github.com/squidfunk/mkdocs-material
  name: material
  custom_dir: overrides

  # for the sidebar/site icon on navbar
  icon:
    logo: material/book-multiple-outline
    repo: fontawesome/brands/gitlab

  features:
    #- announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: recaptime-dev
      repo: squad-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        "organization/about.md": "https://recaptime.dev/about"
        "history.md": "organization/history.md"

# Navigation
nav:
  - Meta: 
    - index.md
    - About: about.md
    - Copyright information: copyright.md
    - Contribute: contribute.md
    - Back to the website: https://recaptime.dev
  - Organization:
    - organization/index.md
    - Anout Recap Time Squad: https://recaptime.dev/about
    - organization/history.md
    - Policies: https://policies.recaptime.dev
    - Squad Handbook:
      - handbook/index.md
      - Onboarding:
        - Onboarding README: handbook/onboarding/index.md
        - handbook/onboarding/preflight-checks.md
  - Community:
    - Projects:
      - projects/index.md
      - Community Lores: projects/lorebooks-wiki.md
  - Donate: https://hcb.hackclub.com/donations/start/recaptime-dev

extra:
  generator: true
  tags:
    Meta: meta
    RecapTime.dev: recaptime-dev
    Hack Club: hackclub
    Community Profiles: profiles
    Team Handbook: handbook
    Projects: projects
  social:
    - icon: simple/mastodon
      link: https://mastodon.xyz/@RecapTimeSquad
      name: Fediverse
    - icon: simple/bluesky
      link: https://bsky.app/profile/recaptime.dev
      name: Bluesky
    - icon: simple/github
      link: https://github.com/recaptime-dev
      name: GitHub
    - icon: simple/gitlab
      link: https://mau.dev/recaptime-dev
      name: GitLab
    - icon: octicons/globe-16
      link: https://recaptime.dev
      name: Main website