# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information, site metadata
site_name: RecapTime.dev Wiki
site_url: "https://wiki.recaptime.dev"
site_author: Recap Time Squad and contributors
site_description: >-
  The squad wiki, consists of both the team handbook, our organizational documents,
  and more.

# Lock the use-directory-urls flag
use_directory_urls: true

# Repository
docs_dir: content
repo_url: https://mau.dev/recaptime-dev/squad/wiki
repo_name: source at Maunium GitLab
edit_uri: blob/main/content/

# Copyright
copyright: >-
  Copyright &copy; 2023-present Recap Time Squad (formerly The Pins Team) and its contributors,
  licensed under CC BY-SA 4.0 for Markdown content and original media and MPL-2.0 for code,
  unless otherwise specified.

theme:
  # https://github.com/squidfunk/mkdocs-material
  name: material

  # for the sidebar/site icon on navbar
  icon:
    logo: material/library
    repo: fontawesome/brands/gitlab

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


  # theme for different themes
  # TODO: Match with our color platte on logo.
  palette:
    - scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: recaptime-dev
      repo: squad-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - social
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        "organization/about.md": "https://recaptime.eu.org/about"

# Navigation
nav:
  - Home: 
    - index.md
    - About the website: about.md
    - Contribute to wiki:
      - contribute/index.md
      - Email patches 101: contribute/email.md
      - For squad members: contribute/squad-members.md
      - Contributing to handbook: handbook/contribute.md
      - "Maintainers' Guidelines": contribute/maintainer-guidelines.md
  - Team:
    - organization/index.md
    - organization/about.md
    - organization/history.md
    - Squad Handbook:
      - handbook/index.md
      - About and History: 
          - handbook/about/index.md
          - Handbook Usage: handbook/handbook-usage.md
          - Handbook Support: handbook/about/support.md
          - Changelog: handbook/changelog.md
      - Onboarding Documentation:
        - handbook/onboarding/index.md
        - Onboarding Checklist: handbook/onboarding/checklist.md
        - handbook/onboarding/issue-tracker-usage.md
        - Onboarding Issue Tracker: "https://mau.dev/recaptime-dev/squad/onboarding"
      - Engineering and Open-source:
        - handbook/engineering/index.md
        - Open-source at RecapTime.dev:
          - handbook/open-source/index.md
          - Open-source Operations/Projects Office: handbook/open-source/office.md
  - Community:
    - Projects:
      - Community Lores: projects/lorebooks.wiki.md